### ISSUE TITLE
doc improvements at package git epic

### ISSUE THREAD

**Issue by Serabe** [src-d/go-git#231]
* [x] Review package doc (remove references to it being a _low-level_ package, etc.)
* [ ] Highlight general steps to work with repositories. Guide the user a bit through the documentation.
* [x] Why `Commit` is treated like a getter while `Push`, `Pull`, etc. are treated like commands?
* [x] Review `References` function documentation:
  * [x] States that it returns a `References` while it does not.
  * [x] Does not specify what the commit input is for.
  * [x] State if the ordering is from newer to older or the other way around.
  * [x] Reword sentence "It stops searching a branch for a file upon reaching the commit were the file was created."
  * [x] Fix _Caveats_ section.
* [x] Document `BlameResult`
* [x] In Blame function:
  * [x] Review output documentation. It states that the last commit is returns, but the return type is not an object.Commit.
  * [x] Review input. It states that there are three inputs, but I can only see two in the signature. What is the commit for? What is the path for? Why is the output documented again after the input with a different version of it?
  * [x] Says that `Line` has a reference to the last commit it was modified on, but the `Line` struct does not seem to have a commit in it.
  * [x] _Each node (line) holds the commit where it was introduced or last modified. To achieve that we use the FORWARD algorithm_. The previous phrase action is _holding a commit_, so I guess we are not using an algorithm to just _hold a commit_ but to find which commit. Rephrase so the pronoun references what is intended to reference.
  * [x] See _General questions about docs_ later in this issue.
* [x] `Line` documentation should be synced with that of `Blame`.
* [x] `XOptions` documentation:
  * [x] Typos fixed in PR #230
  * [x] Explain `Validate`, it seems like a function the user should not care about. If the user should, please state that it is mandatory to be called since it is the one setting the default value.
* [x] `Remote`:
  * [x] ELI5 `Config`.
  * [x] Why do we need to add the remote name to `XOptions` if the action is being done in a Remote?
* [x] `Repository`:
  * [x] Struct doc is messed up.
  * [x] Update `NewXRepository` to reference `go-billy`.
  * [x] Either add the default version (_if you want to use a custom one you need to use the function NewRepository and build you filesystem.Storage_) to all `NewXRepository` methods or, even better, add this to the struct.
  * [x] `NewRepository` is outdated respect to its signature.
  * [x] Unify documentation for getters that return an iterator. Specify clearly that the returned type is an iter and specify the type of the objects being iterated over. In case it is needed, specify the order.
  * [x] What is the difference between `Objects` and `Tags`? Documentation looks the same.
* [x] Storer:
  * [x] Reference where the user can find implementations or create their own. Rewords the part of implementations

## General questions about docs:

* Should we avoid adding TODOs to godocs? IMHO, TODOs are not documentation and the user should not care about them. If anything about them needs to be added to the doc, is which things are not supported.
* Should we avoid stating how things are implemented? IMHO, documentation is not about how something works but why it is there, how the user can take advantage of it, etc. If user needs to know anything about implementation, I would say it is limited to algorithmic complexity.

**Comment by ajnavarro** [comment]
@Serabe what do you want to say with this?:

> Why Commit is treated like a getter while Push, Pull, etc. are treated like commands?

Commit is a getter because you are **getting** a commit object. The Commit action is not implemented yet.

**Comment by Serabe** [comment]
Yay!
